# Generated by Django 2.2.7 on 2019-11-22 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='m_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 22, 20, 10, 33, 126873)),
        ),
    ]
