# Generated by Django 2.2.7 on 2019-11-22 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer_app', '0002_auto_20191122_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='m_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 22, 20, 41, 56, 989060)),
        ),
    ]
