# Generated by Django 2.2.7 on 2019-11-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer_app', '0004_auto_20191122_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('pyment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bkash', 'Bkash')], max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('batch_id', models.CharField(max_length=50)),
                ('expiry_date', models.DateTimeField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('item_information', models.CharField(help_text='only show manufacturer medicine', max_length=50)),
                ('stock', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer_app.Manufacturer')),
            ],
        ),
    ]
