# Generated by Django 2.2.7 on 2019-11-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer_app', '0002_auto_20191122_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('strenght', models.CharField(blank=True, max_length=25, null=True)),
                ('generic_name', models.CharField(max_length=100)),
                ('box_size', models.CharField(max_length=50)),
                ('medicine_shelf', models.CharField(blank=True, max_length=25, null=True)),
                ('medicine_detail', models.TextField(blank=True, null=True)),
                ('medicine_image', models.ImageField(blank=True, null=True, upload_to='medicine_img/')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.CharField(blank=True, max_length=10, null=True)),
                ('menufacturer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Category')),
                ('medicine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.MedicineType')),
                ('menufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer_app.Manufacturer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Unit')),
            ],
        ),
    ]
